'use strict';
// AGENT ⑳: PINE SMITH — for every stock the fleet is actively analysing it writes a
// ready-to-paste TradingView Pine v5 script (RSI + MACD + VWAP + Bollinger + Stochastic +
// ATR stop/target + a composite "bot bias"), and — the important part — it distils that
// analysis into a small structured signal it BROADCASTS on the shared bus (`bus.pine[sym]`)
// so the other agents can read it. The trader folds the confluence in as a bounded
// confirmation nudge; the logger/dashboard surface the fleet-wide view.
//
//  • bus.pine[sym]      = { bias, net, score, sigType, entry, stop, target, rsi, updated }
//  • bus.pineStatus     = { count, written, updated, top:[…] }
//  • bus.pineScript(sym)= full Pine v5 text, generated on demand (used by /api/pine?sym=)
//
// Pine files are also saved to bot-data/pinescripts/<SYM>.pine (top movers each cycle,
// capped so we don't thrash the disk — the cap is logged, nothing is silently dropped).
const fs = require('fs');
const path = require('path');

const CYCLE_MS = 30e3;
const DISK_CAP = 60;                 // full .pine files written per cycle (highest-conviction first)
const DIR = path.join(__dirname, '..', 'bot-data', 'pinescripts');

// distil a market object into a confluence read (mirrors what the Pine script plots)
function analyze(mk) {
  let bull = 0, bear = 0; const notes = [];
  if (mk.rsi != null) { if (mk.rsi < 50) { bull++; notes.push('RSI<50'); } else if (mk.rsi > 70) { bear++; notes.push('RSI>70'); } }
  if (mk.crossUp) { bull++; notes.push('MACD↑'); } else if (mk.crossDown) { bear++; notes.push('MACD↓'); }
  if (mk.vwap != null && mk.price != null) { if (mk.price > mk.vwap) { bull++; notes.push('>VWAP'); } else { bear++; notes.push('<VWAP'); } }
  if (mk.pctB != null) { if (mk.pctB < 0.1) { bull++; notes.push('lowerBB'); } else if (mk.pctB > 0.9) { bear++; notes.push('upperBB'); } }
  if (mk.stochK != null) { if (mk.stochK < 20) { bull++; notes.push('stochOS'); } else if (mk.stochK > 80) { bear++; notes.push('stochOB'); } }
  if ((mk.volSurge || 0) > 1.8) { const c = mk.closes; if (c && c.length >= 2) { if (c[c.length - 1] >= c[c.length - 2]) { bull++; notes.push('vol↑'); } else { bear++; notes.push('vol↓'); } } }
  if (mk.bullPatterns && mk.bullPatterns.length) { bull++; notes.push(mk.bullPatterns[0]); }
  if (mk.bearPatterns && mk.bearPatterns.length >= 2) { bear++; notes.push('bearPatterns'); }
  const net = bull - bear;
  const score = Math.round(Math.max(0, Math.min(100, 50 + net * 10)));
  const bias = Math.max(-1, Math.min(1, net / 5));
  return { bull, bear, net, score, bias, notes };
}

function levels(mk) {
  const entry = mk.price;
  const atrPct = mk.atrPct || 0;
  const stopPct = Math.min(0.04, Math.max(0.012, atrPct * 22));   // same basis the trader's stop uses
  return {
    entry: entry != null ? +entry.toFixed(4) : null,
    stop: entry != null ? +(entry * (1 - stopPct)).toFixed(4) : null,
    target: entry != null ? +(entry * (1 + stopPct * 1.8)).toFixed(4) : null,   // ~1.8R
    stopPct: +(stopPct * 100).toFixed(2),
    tgtPct: +(stopPct * 1.8 * 100).toFixed(2),
  };
}

// build a valid Pine v5 indicator for one symbol, with the live snapshot in the header
function buildScript(sym, mk, a, lv) {
  const stamp = new Date().toISOString().replace('T', ' ').slice(0, 19);
  const biasLabel = a.net > 0 ? `bullish +${a.net}` : a.net < 0 ? `bearish ${a.net}` : 'neutral';
  const cur = mk.currency || '';
  const rsiTxt = mk.rsi != null ? mk.rsi.toFixed(1) : 'n/a';
  const title = ('X2 ' + sym).replace(/"/g, '');
  return `//@version=5
// ============================================================================
//  ${sym} — auto-generated by T212 System X2 · Pine Smith (agent 20)
//  snapshot ${stamp}Z   price ${mk.price} ${cur}   RSI ${rsiTxt}
//  bot bias: ${biasLabel}  (confluence ${a.score}/100 — ${a.notes.join(', ') || 'none'})
//  entry ${lv.entry}   stop ${lv.stop} (-${lv.stopPct}%)   target ${lv.target} (+${lv.tgtPct}%)
//  Paste into TradingView → Pine Editor → Add to chart.  Indicators recompute live.
// ============================================================================
indicator("${title}", overlay=true)

// —— inputs ——
rsiLen   = input.int(14, "RSI length")
bbLen    = input.int(20, "Bollinger length")
bbMult   = input.float(2.0, "Bollinger mult")
stochLen = input.int(14, "Stochastic length")
atrLen   = input.int(14, "ATR length")

// —— indicators (the same set the fleet uses) ——
rsi = ta.rsi(close, rsiLen)
[macdLine, sigLine, hist] = ta.macd(close, 12, 26, 9)
vwapV = ta.vwap
basis = ta.sma(close, bbLen)
dev = bbMult * ta.stdev(close, bbLen)
bbU = basis + dev
bbL = basis - dev
k = ta.stoch(close, high, low, stochLen)
atr = ta.atr(atrLen)

// —— overlays ——
plot(vwapV, "VWAP", color=color.orange)
plot(bbU, "BB upper", color=color.new(color.gray, 55))
plot(bbL, "BB lower", color=color.new(color.gray, 55))

// —— composite bot bias (bull minus bear confluence) ——
bull = (rsi < 50 ? 1 : 0) + (ta.crossover(hist, 0) ? 1 : 0) + (close > vwapV ? 1 : 0) + (close <= bbL * 1.002 ? 1 : 0) + (k < 20 ? 1 : 0)
bear = (rsi > 70 ? 1 : 0) + (ta.crossunder(hist, 0) ? 1 : 0) + (close < vwapV ? 1 : 0) + (close >= bbU * 0.998 ? 1 : 0) + (k > 80 ? 1 : 0)
score = bull - bear
buySig = score >= 2 and rsi < 70
sellSig = score <= -2

// —— ATR stop / target the bot would use ——
stopPct = math.min(0.04, math.max(0.012, (atr / close) * 22))
longStop = close * (1 - stopPct)
longTgt = close * (1 + stopPct * 1.8)

plotshape(buySig, "BUY", style=shape.triangleup, location=location.belowbar, color=color.new(color.green, 0), size=size.small, text="BUY")
plotshape(sellSig, "SELL", style=shape.triangledown, location=location.abovebar, color=color.new(color.red, 0), size=size.small, text="SELL")
bgcolor(buySig ? color.new(color.green, 90) : sellSig ? color.new(color.red, 90) : na)

var line slLine = na
var line tpLine = na
var label lbl = na
if buySig
    line.delete(slLine)
    line.delete(tpLine)
    slLine := line.new(bar_index, longStop, bar_index + 20, longStop, color=color.red, style=line.style_dashed)
    tpLine := line.new(bar_index, longTgt, bar_index + 20, longTgt, color=color.green, style=line.style_dashed)

if barstate.islast
    label.delete(lbl)
    lbl := label.new(bar_index, high, "X2 " + syminfo.ticker + "  RSI " + str.tostring(rsi, "#.0") + "  bias " + str.tostring(score), style=label.style_label_down, color=color.new(color.blue, 70), textcolor=color.white, size=size.small)
`;
}

function start(bus) {
  try { fs.mkdirSync(DIR, { recursive: true }); } catch (e) {}
  bus.pine = bus.pine || {};
  bus.pineStatus = { count: 0, written: 0, updated: null, top: [] };
  const lastHash = {};   // sym -> snapshot signature, so we only rewrite files that changed

  // on-demand full script for any analysed symbol (used by /api/pine?sym=)
  bus.pineScript = (sym) => {
    const mk = bus.market[sym];
    if (!mk || mk.rsi == null || !mk.closes || mk.closes.length < 21) return null;
    const a = analyze(mk); const lv = levels(mk);
    return buildScript(sym, mk, a, lv);
  };

  function cycle() {
    const analysed = Object.keys(bus.market).filter(s => {
      const mk = bus.market[s];
      return mk && mk.rsi != null && mk.price != null && mk.closes && mk.closes.length >= 21;
    });
    const summaries = [];
    for (const sym of analysed) {
      const mk = bus.market[sym];
      const a = analyze(mk); const lv = levels(mk);
      bus.pine[sym] = {
        bias: +a.bias.toFixed(2), net: a.net, score: a.score,
        sigType: mk.sigType || null, rsi: mk.rsi != null ? +mk.rsi.toFixed(1) : null,
        entry: lv.entry, stop: lv.stop, target: lv.target,
        notes: a.notes, updated: new Date().toLocaleTimeString(),
      };
      summaries.push({ sym, net: a.net, score: a.score, bias: a.bias });
    }
    // prune symbols no longer analysed
    for (const sym of Object.keys(bus.pine)) if (!bus.market[sym] || bus.market[sym].rsi == null) delete bus.pine[sym];

    // write the highest-conviction scripts to disk (changed-only, capped)
    let written = 0;
    const ranked = summaries.slice().sort((x, y) => Math.abs(y.net) - Math.abs(x.net) || y.score - x.score);
    for (const { sym } of ranked.slice(0, DISK_CAP)) {
      const p = bus.pine[sym];
      const sig = `${p.net}|${p.score}|${p.sigType}`;
      if (lastHash[sym] === sig) continue;
      lastHash[sym] = sig;
      try { fs.writeFileSync(path.join(DIR, sym.replace(/[^A-Za-z0-9._-]/g, '_') + '.pine'), bus.pineScript(sym)); written++; } catch (e) {}
    }
    try { fs.writeFileSync(path.join(DIR, '_index.json'), JSON.stringify({ updated: new Date().toISOString(), count: analysed.length, top: ranked.slice(0, 40) }, null, 2)); } catch (e) {}

    bus.pineStatus = {
      count: analysed.length, written, updated: new Date().toLocaleTimeString(),
      top: ranked.slice(0, 8).map(r => ({ sym: r.sym, net: r.net, score: r.score })),
    };
    if (analysed.length > DISK_CAP) console.log(`[pine] ${analysed.length} analysed, broadcast all; wrote top ${DISK_CAP} .pine files to disk`);
  }

  setInterval(cycle, CYCLE_MS);
  setTimeout(cycle, 8000);   // first pass once candles have loaded
  console.log('[pine] Pine Smith armed — generates + broadcasts a Pine v5 script per analysed stock');
}
module.exports = { start };
